#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl3,  sonar1,         sensorSONAR_mm)
#pragma config(Motor,  port9,           motorsRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          motorsLeft,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//tmotorVex393_MC29
//tmotorVex393_HBridge

const int SPEEDL = 30;
const int SPEEDR = 30;

const int SONAR_CLOSE = 200;

const bool ENABLED = true;

task main()
{


	motor[motorsLeft] = 0;
	motor[motorsRight] = 0;
	while(ENABLED){

		if(SensorValue(button1)){
			motor[motorsLeft] = SPEEDL;
			motor[motorsRight] = SPEEDR;

			// Keep going until we're close enough.
			while(SensorValue(sonar1) > SONAR_CLOSE);

			motor[motorsLeft] = 0;
			motor[motorsRight] = 0;
		}
	/*
		switch(wheel_state){
			case STOPPED:
				motor[motorsLeft] = 0;
				motor[motorsRight] = 0;

				break;

			case FORWARDS:
				motor[motorsLeft] = SPEEDL;
				motor[motorsRight] = SPEEDR;

				wheel_state = STOPPED;
				break;
		}*/
	}
	// Keep sensor values open
	while(1);
}
